dune:
  api_key: ${DUNE_API_KEY}
  namespace: surgence_lab
  base_url: https://api.dune.com/api/v1
  tables:
    logs: incentiv_logs_v2
    blocks: incentiv_blocks_v2
    transactions: incentiv_transactions_v2
