incentiv:
  contracts:
    mailbox: ${INCENTIV_MAILBOX_ADDRESS}
    hyperlane_router: ${INCENTIV_HYPERLANE_ROUTER_ADDRESS}
    dex_pool: "0xf9884c2A1749b0a02ce780aDE437cBaDFA3a961D"
  topics:
    transfer: "0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef"
    approval: "0x8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b2291e5b200ac8c7c3b925"
    swap_v3: "0xc42079f94a6350d7e6235f29174924f928cc2ac818eb64fed8004e115fbcca67"
    received_transfer_remote: "0xba20947a325f450d232530e5f5fce293e7963499d5309a07cee84a269f2f15a6"
    process: "0x0d381c2a574ae8f04e213db7cfb4df8df712cdbd427d9868ffef380660ca6574"
